name: Deploy_Node_Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

      - name: Build Docker Image
        run: docker build -t ajinthomas619/picsaly-client ./client --build-arg REACT_APP_NODE_ENV=production --build-arg REACT_APP_BASE_URL=${{ secrets.VITE_APP_BASE_URL }}

      - name: Publish Image to Docker Hub
        run: docker push ajinthomas619/picsaly-client:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from Docker Hub
        run: docker pull ajinthomas619/picsaly-client:latest

      - name: Delete old container
        run: docker rm -f picsaly-client || true

      - name: Run Docker container
        run: docker run -d -p 3000:80 --name picsaly-client ajinthomas619/picsaly-client:latest
